version: "3"
services:
  db:
    container_name: db
    image: mongo:7.0.0
    ports:
      - "4000:27017"
    restart: always

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}
    restart: no

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
    restart: no

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://db:27017
      - DBNAME=history
    restart: no
